fix error for CD-3

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -17,17 +17,20 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 20 # Versiyani moslashtiring
+          node-version: 18
 
       - name: Install Dependencies
-        run: npm ci # npm ci ni sinab ko‘ring
+        run: npm ci
 
       - name: Run Tests
         run: npm run test
-        continue-on-error: true # Test xatosi bo‘lsa ham davom etsin
+        continue-on-error: true
 
       - name: Build Project
         run: npm run build
+
+      - name: Check Build Output
+        run: ls -la dist || echo "Dist folder not found"
 
       - name: Upload Build Artifact
         uses: actions/upload-artifact@v3
